### ISSUE TITLE
CSS 列表

### ISSUE THREAD

**Issue by LeeJim** [LeeJim/blog#1]
ul的list-style速记写法可以接受三个参数：type、position、image

``` css
ul {
    list-style: <list-style-type> || <list-style-position> || <list-style-image>;
}
```

举个栗子

``` css
ul {
    list-style: square outside none;
}
```

当然，还有普通写法

``` css
ul {
 list-style-type: square;
 list-style-position: outside;
 list-style-image: none;
}
```

list-style-type有以下可选值
- disc
- circle
- square
- decimal
- decimal-leading-zero
- lower-roman
- upper-roman
- lower-greek
- lower-latin
- upper-latin
- armenian
- georgian
- lower-alpha
- upper-alpha
- none

list-style-position有以下可选值
- inside
- outside

list-style-image则只接受图片路径

``` css
ul {
    list-style-image: url(images/list-style.png);
}
```
