### ISSUE TITLE
css trick

### ISSUE THREAD

**Issue by LeeJim** [LeeJim/blog#4]
多行文字溢出加省略号(-webkit-line-clamp限制行数)

``` css
.text-overflow {
  width: 200px; 
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
```

局部滚动

``` css
  .wrap {
    -webkit-overflow-scrolling : touch;
  }
```
