### ISSUE TITLE
LESS

### ISSUE THREAD

**Issue by LeeJim** [LeeJim/blog#7]
## 变量

``` less
@link-color:        #428bca; // sea blue
@link-color-hover:  darken(@link-color, 10%);
```
### 变量插入

变量还可以放在其他地方使用，例如选择器，属性，URLs和@import声明
#### 选择器

``` less
// Variables
@my-selector: banner;

// Usage
.@{my-selector} {
  margin: 0 auto;
}
```
#### 属性

``` less
@property: color;

.widget {
  @{property}: #0ee;
  background-@{property}: #999;
}
```
#### URLs

``` less
// Variables
@images: "../img";

// Usage
body {
  background: url("@{images}/white-sand.png");
}
```
#### @import

``` less
// Variables
@themes: "../../src/themes";

// Usage
@import "@{themes}/tidal-wave.less";
```
### 变量名声明变量

``` less
@fnord:  "I am fnord.";
@var:    "fnord";
content: @@var; //"I am fnord."
```
